version: "3.8"

services:
  minio:
    container_name: minio-local
    image: quay.io/minio/minio
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      - MINIO_ROOT_USER=ROOTUSER
      - MINIO_ROOT_PASSWORD=CHANGEME123
    volumes:
      - ${HOME}/minio/data:/data
    command: server /data --console-address ":9090"

# docker run \
#    -p 9000:9000 \
#    -p 9090:9090 \
#    --user $(id -u):$(id -g) \
#    --name minio1 \
#    -e "MINIO_ROOT_USER=ROOTUSER" \
#    -e "MINIO_ROOT_PASSWORD=CHANGEME123" \
#    -v ${HOME}/minio/data:/data \
#    quay.io/minio/minio server /data --console-address ":9090"



